[package]

name = "pam"
description = "PAM bindings for Rust"
version = "0.0.3"
authors = [ "Jesse Hallett <jesse@galois.com>" ]
documentation = "https://tozny.github.io/rust-pam/pam/"
homepage = "https://github.com/tozny/rust-pam"
repository = "https://github.com/tozny/rust-pam.git"
readme = "README.md"
keywords = ["pam", "ffi", "linux", "authentication"]
license = "MIT"

[lib]
name = "pam"

[dependencies]
libc = "~0.1.5"
